/* 
 * Registration-client-api
 *
 * Interage com o registration server (eureka) para registar esta instância ou obter servidores com o qual pode comunicar
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Pt.Unl.Fct.Miei.Usmanagement.Manager.Api;
using Pt.Unl.Fct.Miei.Usmanagement.Manager.Model;
using Pt.Unl.Fct.Miei.Usmanagement.Manager.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Pt.Unl.Fct.Miei.Usmanagement.Manager.Test
{
    /// <summary>
    ///  Class for testing Endpoint
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EndpointTests
    {
        // TODO uncomment below to declare an instance variable for Endpoint
        //private Endpoint instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Endpoint
            //instance = new Endpoint();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Endpoint
        /// </summary>
        [Test]
        public void EndpointInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Endpoint
            //Assert.IsInstanceOfType<Endpoint> (instance, "variable 'instance' is a Endpoint");
        }


        /// <summary>
        /// Test the property 'InstanceId'
        /// </summary>
        [Test]
        public void InstanceIdTest()
        {
            // TODO unit test for the property 'InstanceId'
        }
        /// <summary>
        /// Test the property '_Endpoint'
        /// </summary>
        [Test]
        public void _EndpointTest()
        {
            // TODO unit test for the property '_Endpoint'
        }

    }

}
